BaseURL = "http://replace-this-with-your-hugo-site.com/"
Title = "Atomic-Package"
languageCode = "ja"

[Params]
description = "APB CSS (Atomic Parts Base CSS) + JavaScript framework."
author = "Daisuke Takayama"

